### PR TITLE
Rails 6.0.0 compatibility fixes

### LINKED ISSUE #407: Order Column collides with Rails 6 - wrong number of arguments (given 0, expected 1)
using `@model.children ` results in
`wrong number of arguments (given 0, expected 1)`

Rails 6.0.0.rc1 seam to have its own ` order_column ` Method, see this commit: https://github.com/rails/rails/commit/cb0299c9eba6463085130debda6347abf9683463

not sure if it's directly related to this Rails 6 Feature
https://blog.bigbinary.com/2019/04/16/rails-6-adds-implicit_order_column.html

### PR DESCRIPTION
**Pull request by damianlegawiec**
Fixes #407

### CODE REVIEW

**Comment by parndt** [comment]
Looks like the only issue is with mariadb on ruby 2.6.3, Rails 5.2
https://travis-ci.org/collectiveidea/awesome_nested_set/jobs/566549468

Thanks for doing this

**Comment by damianlegawiec** [comment]
Hey @parndt MariaDB issue resolved plus updated to use final Rails 6.0 release

**Comment by parndt** [comment]
@damianlegawiec wooohooo thank you!!

**Comment by damianlegawiec** [comment]
Hey @parndt since Rails 6.0 is now released could you please release a new version on RubyGems? Thanks :)

**Comment by tvdeyen** [comment]
@damianlegawiec thanks for working on this :clap:

**Comment by parndt** [comment]
@damianlegawiec 	yes, I think version `3.2.0`, because I'm not sure it justifies a bump to `4.0.0`... what do you think?

**Comment by damianlegawiec** [comment]
@parndt yup, `3.2.0` sounds good!

**Comment by parndt** [comment]
Gem pushed! https://rubygems.org/gems/awesome_nested_set/versions/3.2.0

**Comment by phantomwhale** [comment]
Quick note here, as noted in the spree link above, that this issue also manifests in rails 5.2 - namely in 5.2.4 onwards. I started seeing `wrong number of arguments (given 0, expected 1)` - easily fixed with a quick bundle update on this gem, but google looked over this (as it was marked as Rails 6.0). Yes, I basically just typed out most of what I searched for in the hope it'll get caught in the net of whoever might stumble over this issue next.

**Pull request merged**
