### PR TITLE
add Rails 5.0 support

### PR DESCRIPTION
**Pull request by krzysiek1507**

### CODE REVIEW

**Comment by krzysiek1507** [comment]
`Gem::InstallError: mime-types-data requires Ruby version >= 2.0.`

**Comment by danielmorrison** [comment]
Add this to the Travis build.

**Comment by krzysiek1507** [comment]
@danielmorrison ruby < 2.2.2 failing as expected on Rails 5, but `rbx-2` and `jruby-9.1.1.0` are red too. Is this ok? https://travis-ci.org/collectiveidea/awesome_nested_set/builds/133150363

**Comment by krzysiek1507** [comment]
I can add these to `allow_failures` section

**Comment by danielmorrison** [comment]
You can also exclude. I did similar on another project: https://github.com/collectiveidea/audited/blob/master/.travis.yml

**Comment by krzysiek1507** [comment]
@danielmorrison excluded

**Comment by krzysiek1507** [comment]
@danielmorrison could you release e.g. 4.0.beta?

**Comment by danielmorrison** [comment]
3.1.0 released as I don't think we have any breaking changes.

**Comment by krzysiek1507** [comment]
Thanks.

**Pull request merged**
