### PR TITLE
Fix migration in README.md

### PR DESCRIPTION
**Pull request by takashi**
resolves https://github.com/collectiveidea/awesome_nested_set/issues/297

### CODE REVIEW

**Comment by parndt** [comment]
Thanks! The rest of the readme uses hashrocket syntax, would you mind if we maintained that to reduce potential confusion?

**Comment by takashi** [comment]
@parndt upps, sorry for that, and I don't mind if you maintain it :)

**Comment by parndt** [comment]
Sure, thanks :)

**Comment by takashi** [comment]
:D

**Pull request closed without merging**
