### PR TITLE
Add support for Rails 7

### PR DESCRIPTION
**Pull request by peterberkenbosch**

### CODE REVIEW

**Comment by mindtonic** [comment]
+1 Please!

**Comment by MrEmelianenko** [comment]
+1

**Comment by MrEmelianenko** [comment]
As a temporary solution you can add this to your Gemfile:

```ruby
gem "awesome_nested_set", github: "peterberkenbosch/awesome_nested_set", branch: "rails-7-support"
```

**Comment by peterberkenbosch** [comment]
Looking at fixing the failing specs around ruby versions:

```
Bundler found conflicting requirements for the Ruby version:
    In rails_7_0.gemfile:
      Ruby
  
      awesome_nested_set was resolved to 3.4.0, which depends on
        Ruby (>= 2.0.0)
  
      rails (~> 7.0.0) was resolved to 7.0.0, which depends on
        Ruby (>= 2.7.0)
  Took   3.44 seconds
```

**Comment by parndt** [comment]
@peterberkenbosch perhaps we can address different versions like this one so the library itself isn't coupled to what Rails 7 supports 
https://github.com/norman/friendly_id/pull/984

thanks for looking at this

**Comment by peterberkenbosch** [comment]
Hey @parndt. Good find.. on it! Thanks.

**Comment by andrewhampton** [comment]
@peterberkenbosch I've finished getting the tests passing and opened a PR to [this branch on your repository](https://github.com/peterberkenbosch/awesome_nested_set/pull/1).

@parndt as part of that change, I had to drop the combustion gem. The older version currently required by awesome_nested_set doesn't work with rails 7. I initially tried updating combustion, but the API has changed and you can no longer pass in the database config you want. So I'm just using the rails tasks directly and dropped that dependency. Hopefully that's ok?

**Comment by peterberkenbosch** [comment]
Thanks @andrewhampton!

**Review by parndt — APPROVED** [review]

**Pull request merged**
