### PR TITLE
Update counter cache correctly for STI records

### LINKED ISSUE #415: `counter_cache` doesn't update the parent which is different class from child's counter
We have STI classes like this:

```ruby
class Parent
  acts_as_nested_set counter_cache: :counter
end

class Foo < Parent
end

class Bar < Parent
end
```

Then, when I try to move a Bar instance under the Foo instance (doing `bar.move_to_child_of foo`),
I'd like to increment `counter` field of the parent class Foo, but it's impossible because the increment is done by doing internally like:

```ruby
self.class.increment_counter(acts_as_nested_set_options[:counter_cache], new_parent)
```

It virtually equals to the following in my case:

```ruby
Bar.increment_counter(:counter, foo)
```

But they're an STI, so the SQL which will be performed is like:

```sql
UPDATE parents SET counter = COALESCE(counter, 0) + 1 WHERE parents.type = 'Bar' AND parents.id = 123
```

It updates no records because id=123 is a type of "Foo".
So I guess the codes in `update_counter_cache` should be like:

```ruby
new_paraet.class.increment_counter(acts_as_nested_set_options[:counter_cache], new_parent)
```

If my guess is right, I'm willing to open a PullReq for it :)
Thanks.

### PR DESCRIPTION
**Pull request by issei-m**
Fixes #415

### CODE REVIEW

**Comment by parndt** [comment]
Makes sense - thanks @issei-m 👏

**Review by parndt — APPROVED** [review]

**Comment by issei-m** [comment]
@parndt Thanks for merging it quickly! Do you have a plan for when to release it? I'd be glad if I could incorporate it into our PJ soon :)

**Comment by parndt** [comment]
@issei-m I've released it as version 3.4.0 - enjoy

**Comment by issei-m** [comment]
Excellent! Thank you!

**Pull request merged**
